name: Aprendiendo Github Actions
run-name: Este es un workflow simple para aprender github actions
on: [push]
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Definir variable
        run: echo "USERNAME= ${{ github.actor}}" >> $GITHUB_ENV
      - name: Correr script
        run: python main.py