name: Usando triggers en mi Workflow
run-name: Un workflow con triggers
on:
    push:
        branches:
            - main
            - aprendiendo-github-actions
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
        paths:
            - '**.py'
    schedule:
        - cron: '0 0 * * *'
    issues:
        types:
            - labeled
    workflow_dispatch:
        inputs:
            lenguaje_favorito:
                description: '¿Cuál es tu lenguaje de programación favorito?'
                required: true
                type: choice
                options:
                    - 'Python'
                    - 'JavaScript'
                    - 'Java'
                    - 'C#'
                    - 'PHP'
                    - 'Ruby'
                    - 'Go'
                    - 'Swift'
                    - 'Kotlin'
                    - 'Rust'
                    - 'TypeScript'
            nombre:
                description: '¿Cuál es tu nombre?'
                required: true
                type: string
                default: 'Paulo'
jobs:
    hola-mundo-manual:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Definir nombre
              run: echo "USERNAME= ${{ inputs.nombre }}" >> $GITHUB_ENV
            - name: Definir lenguaje
              run: echo "LENGUAJE= ${{ inputs.lenguaje_favorito }}" >> $GITHUB_ENV
            - name: Correr script
              run: python hola_lenguaje.py
    hola-mundo:
        if: ${{ github.event_name != 'workflow_dispatch' }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Definir nombre
              run: echo "USERNAME= ${{ inputs.nombre }}" >> $GITHUB_ENV
            - name: Correr script
              run: python main.py